name: Build and deploy .NET Core application to Web App BusStationTicketManagement20250407050228
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: BusStationTicketManagement20250407050228
  AZURE_WEBAPP_PACKAGE_PATH: Bus Station Ticket Management/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: Bus Station Ticket Management
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
      
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    